# Generated by Django 5.2.5 on 2025-08-20 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, help_text='Título oficial de la película.', max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, help_text='Sinopsis o notas adicionales.', verbose_name='descripción')),
                ('duracion_min', models.PositiveSmallIntegerField(help_text='Duración total en minutos (≥ 1).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='duración (min)')),
                ('clasificacion', models.CharField(blank=True, choices=[('TP', 'Todos los públicos'), ('+7', 'Mayores de 7'), ('+12', 'Mayores de 12'), ('+16', 'Mayores de 16'), ('+18', 'Mayores de 18')], help_text='Por ejemplo: TP, +7, +12, +16, +18.', max_length=4, verbose_name='clasificación por edades')),
                ('poster_url', models.URLField(blank=True, help_text='Enlace a la imagen del póster (opcional).', verbose_name='URL del póster')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True, help_text='Fecha y hora de inicio de la sesión.', verbose_name='inicio')),
                ('sala', models.CharField(default='Sala 1', help_text='Nombre o identificador de la sala.', max_length=20, verbose_name='sala')),
                ('filas', models.PositiveSmallIntegerField(default=10, help_text='Cantidad de filas (p. ej., 10 → A-J). Debe ser ≥ 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='nº de filas')),
                ('columnas', models.PositiveSmallIntegerField(default=12, help_text='Asientos por fila (p. ej., 12 → 1-12). Debe ser ≥ 1.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='nº de columnas')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='cine.pelicula', verbose_name='película')),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(help_text='Letra de la fila (A, B, C, ...).', max_length=1, validators=[django.core.validators.RegexValidator(message='Debe ser una única letra.', regex='^[A-Za-z]$')], verbose_name='fila')),
                ('numero', models.PositiveSmallIntegerField(help_text='Número de asiento dentro de la fila (≥ 1).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Correo electrónico asociado (opcional).', max_length=254, verbose_name='email del comprador')),
                ('estado', models.CharField(choices=[('reservada', 'reservada'), ('pagada', 'pagada')], default='reservada', max_length=12, verbose_name='estado')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='cine.sesion', verbose_name='sesión')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['pelicula', 'inicio'], name='sesion_pelicula_inicio_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('inicio', 'sala'), name='unique_sesion_sala_fecha'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['sesion', 'estado'], name='entrada_sesion_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(fields=('sesion', 'fila', 'numero'), name='unique_asiento_por_sesion'),
        ),
    ]
